config:
  azure-native:clientId: 92261697-6976-49ea-a6b0-82e81b393e1c
  azure-native:clientSecret:
    secure: AAABAO3thLQWzMtLYiKcBimqsmUaSu3s35oBaq9iNg508JRUvl0F8aPEFEFxchQi2BWTm2mHw2ZXs52nCekrKrnFJqIwZOBn
  azure-native:location: westeurope
  azure-native:subscriptionId: d22db5bd-ca9a-447c-9b1b-dc56aca401d7
  azure-native:tenantId: c7837eb3-77ca-413b-8653-c97b08886678
