config:
  azure-native:clientId: 232e73fa-4bf2-44c5-9b91-3b5f05d52d7e
  azure-native:clientSecret:
    secure: AAABAOtlkqh/zUC8IhSCmH5iS5yRxTU545VXCoaJ7Z7A2hJv9SEVXQlrYFOTuwWvyyO2baZfo4k5/iRgKSBtey0Bi24fHVF4
  azure-native:location: westeurope
  azure-native:subscriptionId: d22db5bd-ca9a-447c-9b1b-dc56aca401d7
  azure-native:tenantId: c7837eb3-77ca-413b-8653-c97b08886678
  cloudflare:apiToken:
    secure: AAABAH02+u/1Jofp4mxQSXvLvu4L+KluTtnuGZ/2ZzcflosCpIdv7mZvU9fpByxnAFgRTSww+E31pYZ9ltASCJA0AaOS5wdY
  upstash:apiKey:
    secure: AAABAA4uczsIqJBQeivalxPglUnyRW7kDeBxW7rlBSyz1mj6oxBycKs33c0MtI/Fc1EpFhWKE8V916kDWT9S2KyOs4E=
  upstash:email:
    secure: AAABAGOXr69vNhq6ckxfei1zsrXIM4cq4Yv6KA7esdbmZ2a2oA83Rhsna6+7KWXiyixY4zQKeUeWIjUByQ==
  vercel:apiToken:
    secure: AAABAI2nB2TbUVhPjYPQl8ue64+9LtqJTEL6408tY6rrPaLSXZVlcDhMxLltWpW14J1po+76cH4=
  vercel:team: team_Ade0MlfC3211ml3wYJZ4c9hn
  workingparty:jwtsecret:
    secure: AAABAG9zbmY5t4S27H4QuaCj35mVe8NVmCKEgzry2ajqbYy+ohranbTX3sY6N2A7rkBnk0LI6Ow/1Pp7YJk6shGzMpUe3sVJvBk/XM+Yn7WiDeH+16gnTmZ2sUWSAFDP
  workingparty:openaikey:
    secure: AAABAPdimdpTlypx46e1fqyCS3zqcYZwWUuAx37ZyYZIx1Squ3yn9fiHQGXzBq5VAuIizLYm3HpkqcxvuV/QFw1YfKLcWYM8R04pRQCZvQVjH9o=
  workingparty:stripepublic: pk_test_51Oo4eBKrhEdchP2TpPJFSb1ktE3fc7ROYF7F92XC39ImPQgmzNWpAQpywBTZqYWMEBAGWJtnhekH6IKaoukUUJ5U00yjMFfDGh
  workingparty:stripesecret:
    secure: AAABAEoepFSvUJLmr/2PJdR2FnoRH76wQ0DtHgTJ4Zrjjm6Uz4mGxElfsjwQxal9FVshQNDGKf8hSWI03UI36VM/RrN/COxQrtjDEB9eRddWL0m+42xj7Atz5PKvZvMDhxuMCfrmqDgGgwaZ+/xjki+qR2rSRwnSkqDYyYCrbQGaRwy+dPsMoLaBFQ==
  workingparty:stripewebhooksecret:
    secure: AAABAP7y3B6EPrYjkdEpLV9B8WEoitSbd/6Y20BBV6J/uDoMOAAQfHf8af85URCL1+knycDLgYjr0ZD2V33NOJ9CpTdK3A==
  workingparty:zoneid:
    secure: AAABAKPhChxDtSh0Awbi9M5qGDOO7imXSeho3ge9StCDHOY1a30L6vFuuNnMsKxr4rWjPMf3gpeTUxj5G1AyVg==
