config:
  azure-native:clientId: 232e73fa-4bf2-44c5-9b91-3b5f05d52d7e
  azure-native:clientSecret:
    secure: AAABAKAr6KkmZCHYTLADEoq1aR1jj33GjYclq5ZyRrxs4tOQUm8s89nKkt6yhxZvG9GYAFUEnkEJMr7lVnC3fuL2Uj7hTQJt
  azure-native:location: westeurope
  azure-native:subscriptionId: d22db5bd-ca9a-447c-9b1b-dc56aca401d7
  azure-native:tenantId: c7837eb3-77ca-413b-8653-c97b08886678
  cloudflare:apiToken:
    secure: AAABAO4ehCBlmEZotEtf/cPBoPatuO/roiMsdUFso/loruEqous1Pjpt000aHkt257BA3yw9hXRiLoYYHGGmJCvPRBbcYldT
  vercel:apiToken:
    secure: AAABACJmxGvWoeoGVWKuzn1fw+mjEt/GYKPMSTVb68RhEyEYzHfjBHgCz6IWwNehCbLuwCUkzcA=
  vercel:team: team_Ade0MlfC3211ml3wYJZ4c9hn
  workingparty:jwtsecret:
    secure: AAABAM70EzVig9lHo5fx0jSK3+gL4S5j5A9ruALqecytYnHfl6fzCDK7vpXh9/9TptxWh9zNPHzNcrbP5xIr/SUo+r0ht56kmSOB+YGkAEffhN2A7sTl4SQR6N7rQ0oJ
  workingparty:openaikey:
    secure: AAABAKqH3foxRKZwpAROBKMr33uzPnIKSZsbgmmBENodJDG9tV3wvncw9/y89lbozHu0u/SJC08MPkucnIJqZWcKWiAEDWhiZVywQGPOeWhl+p0=
  workingparty:stripepublic: pk_test_51OyzhqGtiJHisrYaQsoHCDxl7CxNqxBtt4KXxHJuXo8eaWP99EugXa1GMj6uKgvmMtNEzBjslOkvtAMMJUaErLgL00UW3jsgBL
  workingparty:stripesecret:
    secure: AAABAHQz2tBwRDff4mTMZBU1WgYNQsDVQ2xvwPaxQQon5bCoLoMyUdGxrsCnGKa2i/t3lS2v23QTib4sDv+PqaIae+noPFCkjYjV7t2Y48ZigfRb/0QtjObZDpuAjeMnHkp3cY9CB7O9msM+t8uf8d7mP5ErzM+xT9YHCmFWwSVuW0dAD4BS/+48tA==
  workingparty:stripewebhooksecret:
    secure: AAABAIX6Mo/iLogSstuSuK7B/y0JDL7+hFr2MSAYouCnjzyur7wvlL769or5Bpf4GZzDSgqX/53cmIaUQze5omZ0lsmpvQ==
  workingparty:zoneid:
    secure: AAABAPrl2wRsB1uolAsq6TO5vkKEiQir3K91uDebkilqobe923ShzF0SvTanaCk8WmITSV97BeCxNAji8mwkNg==
