config:
  azure-native:clientId: f72781c2-20ca-47bf-bdfc-a39343fbaede
  azure-native:clientSecret:
    secure: AAABAKNv1KwWFJpsVdaGYA6F6CcjxQ/stOwVwh99ZQzIA3K/9WD9JOITtbIndAgOdipNfvlmmHASUOjuQsW6tosOXJKaVtgk
  azure-native:location: westeurope
  azure-native:subscriptionId: d22db5bd-ca9a-447c-9b1b-dc56aca401d7
  azure-native:tenantId: c7837eb3-77ca-413b-8653-c97b08886678
  cloudflare:apiToken:
    secure: AAABAAqPzyAV9mvmavpxCxB+Ws+snM4JK8mNiAxa+WqmzniW5gNmJpHXGgXZI69SkL251Lhhrp43BUrvHnTEbAFf3lG8/Wsl
  uier:zoneid:
    secure: AAABAJK2ySr7F+7XlKpMjtxnW6fzUm06HdbFbM5lVT6isD2OQ36zJO+sg5NVhGrF+SnbDe4wYL1TIyDsDR7Sxw==
  vercel:apiToken:
    secure: AAABAHSKTxqe8XeID/RzkDXbcDJfXj160EL8WdulCSF/a0ufwimxDyklpBI/jC0QjFFb7sQslL0=
  vercel:team: team_Ade0MlfC3211ml3wYJZ4c9hn
