config:
  azure-native:clientId: f72781c2-20ca-47bf-bdfc-a39343fbaede
  azure-native:clientSecret:
    secure: v1:ePO4EE06ie85SDEb:PMasf7Ly1IQsxvaG34NwGTWVPtYlBayqBhND8BbqeSybLKA9xvbDPlMv82AoCTEFxz3IOPYJbNc=
  azure-native:location: westeurope
  azure-native:subscriptionId: d22db5bd-ca9a-447c-9b1b-dc56aca401d7
  azure-native:tenantId: c7837eb3-77ca-413b-8653-c97b08886678
  cloudflare:apiToken:
    secure: v1:tMZJAXey+3No4uL4:eCoR33IIUYQ8UP/KoU3tYHyMMNV87g1CAWyDMM/yBdCEuBK9r3Tl4GJlieKSlEWnL01FZtcUC5E=
  uier:zoneid:
    secure: v1:J6ggeYv1vDbBiw74:BNvL9rt5MqZbi38sZVNlQRJ37k9tR9DK8wQje9lkaeFVMzy0XB0NKghhv/9REnAs
  vercel:apiToken:
    secure: v1:A0VrCPF/0+pxKY2B:zrXfJ07lXF6EE9GuRnSDVyc153j95NVS738PFqm/aZKgmxlkoraOmg==
  vercel:team: team_Ade0MlfC3211ml3wYJZ4c9hn
secretsprovider: azurekeyvault://vault-pulumib5f713d9.vault.azure.net/keys/pulumi-backend/31ac989112f948b299b6e92d2ba96695
encryptedkey: Y3RPb1pNMW9PNXhLLTFuc3dkOVNsX25XWFlOTTFXNTlORkN0WFVrd1Y4djJSR1RKUlZGR3JHTmJUUXd6RnV1VUEtd3k0dEhaYlVfSndHVkw2emlIQmVlX3c3T0Y2Ym5TUVpMT250cEFXLUtlOWVCY1g0Z3R1a3IxZTVWMnJhZGJpQkNuQ1l3VU9POUZOdGJTTHZpeEhXbkt1bkdVOHVmcWVYMFAzV2xXVnk2dkF0aGw2U0xlanVwQmpKbUhmR0tvMzVwLVdyZFpHWWVFUXBUemhKMGNielBYZlRZMm4yRnNaOHlSM0dzRFRTNlVOMlJoOEJ1c1ZKYUg5a1N5T2otY05DV3Y0RWVOaThQUmRkSnhaV05ONldoMjFHeEd1Mkh0VU02cUtOSkpVQmJDbUlQb3F3Ti1rN3M2enE0bGF3WTdZczJCVUZvb1pLVDBkVXVpX0VDQkxR
